logging:
  log_interval: 500
  save_interval: 1000
  run_id: '999943'
  run_name: NLF_TLDR_keerthi
  save_dir: /keerthi_save_path
  wandb_entity: sauc-ms-thesis
  wandb_log: true
  wandb_project: nlf
model:
  policy_model:
    input_padding_side: left
    name_or_path: CarperAI/openai_summarize_tldr_sft
  ref_policy:
    name_or_path: CarperAI/openai_summarize_tldr_sft
  tokenizer:
    name_or_path: EleutherAI/gpt-j-6b
train:
  clip_grad: false
  cuda_deterministic: true
  entropy_coef: 0.06
  lr: 2e-5
  max_grad_norm: 1.0
  max_input_length: 1024
  seed: 42
  total_episodes: 40960
  warmup_ratio: 0.05
  training_batch_size_per_card: 8
  num_samples_per_prompt: 10
  num_feedback_categories: 4
  max_new_tokens: 64
  unfrozen_layers_ratio: 0.3
  datapool_drop_factor: 1.0
