compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: tasks/hh/configs/ds_config_ds_opt_ds_sch_cpu_off.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false