logging:
  log_interval: 500
  save_interval: 1000
  run_id: '19994'
  run_name: QUARK_TLDR_run
  save_dir: output
  scratch_dir: scratch
  wandb_entity: my_entity
  wandb_log: true
  wandb_project: my_project
model:
  policy_model:
    input_padding_side: left
    name_or_path: CarperAI/openai_summarize_tldr_sft
  ref_policy:
    name_or_path: CarperAI/openai_summarize_tldr_sft
  tokenizer:
    name_or_path: EleutherAI/gpt-j-6b
reward:
  batch_size: 96
  half: true
  load_state_dict: true
  max_length: 550
  name_or_path: CarperAI/openai_summarize_tldr_sft
  state_dict_path: save_path/reward_model/rm_checkpoint/pytorch_model.bin
train:
  clip_grad: false
  cuda_deterministic: true
  entropy_coef: 0.06
  kl_coef: 0.05
  lr: 2e-5
  max_grad_norm: 1.0
  max_input_length: 1024
  max_new_tokens: 64
  seed: 42
  total_episodes: 40960
  warmup_ratio: 0.05
  training_batch_size_per_card: 8
  num_quantiles: 5
  num_samples_per_quantile: 2
  unfrozen_layers_ratio: 0.3
  datapool_drop_factor: 1.0
